### ISSUE TITLE
RFC 287 compatibility

### ISSUE THREAD

**Issue by simonihmig** [DockYard/ember-maybe-in-element#13]
Similar to https://github.com/kaliber5/ember-in-element-polyfill/issues/5, this is not playing well with the actual semantics of the RFC:
* Does not allow to pass `insertBefore`
* Does not have replace by default semantics

In v0.2.0 of `ember-in-element-polyfill` I fixed those issues on my part. It would be nice if `ember-maybe-in-element` would play nicely with that. So I would suggest:
* to add `ember-in-element-polyfill` as a dependency here
* change the AST transform to use only the public `in-element` (which `ember-in-element-polyfill` will transform to `-in-element`), and to pass `insertBefore` down to `in-element` if present

Note that `ember-in-element-polyfill` will skip any transforms as soon as the public `in-element` becomes part of a future Ember release, so that will also make you not have to care about it.

**Comment by cibernox** [comment]
Yeah, when I saw your polyfill I thought I should update this addon. I'll try to do it over the weekend

**Comment by snewcomer** [comment]
Looks like this is completed!
