### ISSUE TITLE
v0.4.0 is not on GitHub

### ISSUE THREAD

**Issue by buschtoens** [DockYard/ember-maybe-in-element#17]
`v0.4.0` is published on npm, but was not pushed to GitHub.
https://www.npmjs.com/package/ember-maybe-in-element

**Comment by jelhan** [comment]
`0.2.0` has been republished as `0.4.0`: https://github.com/DockYard/ember-maybe-in-element/pull/16#issuecomment-509412852

**Comment by buschtoens** [comment]
Thanks for pointing this out! I'll keep this issue open, until `v0.4.0` or `v0.5.0` are published on GitHub, so others see it right away.

**Comment by snewcomer** [comment]
Published 0.4.0!  Next is #26 so we can bump to 1.0.0 and then #25
